spring:
  application:
    name: eureka
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false