server:
  port: 8082
spring:
  application:
    name: fraud
  datasource:
    username: davidwrz
    url: jdbc:postgresql://localhost:5433/postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true